stages:
  - dev-deploy

dev_deploy:
  stage: dev-deploy
  only:
    - development
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - echo "$DEV_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $DEV_IP_ADDRESS >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh $DEV_SERVER_USER@$DEV_IP_ADDRESS "
        cd /var/www/html/dev/JAIM-Investor &&
        git stash &&
        git pull origin development &&
        npm i &&
        npm run build &&
        sudo systemctl restart nginx
      "


